# Generated by Django 3.0.3 on 2020-04-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='picture',
            field=models.ImageField(default='/media/menu/defaultmenuitem.png', upload_to='media/menu/'),
        ),
    ]
