# Generated by Django 3.0.3 on 2020-04-16 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_menuitem_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='order_total',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
