# Generated by Django 3.0.3 on 2020-03-30 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0002_orderlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(max_length=300)),
                ('quantity', models.PositiveIntegerField()),
                ('order_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_request', to='customer.OrderList')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_request', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
