# Generated by Django 3.0.3 on 2020-03-30 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_orderrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='menuItems',
        ),
    ]
