# Generated by Django 3.0.3 on 2020-04-16 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_orderlist_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='order_total',
        ),
    ]
