# Generated by Django 3.0.3 on 2020-04-17 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_remove_orderlist_order_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
