# Generated by Django 3.0.3 on 2020-04-18 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('1', 'customer'), ('2', 'cashier'), ('3', 'kitchen'), ('4', 'manager')], max_length=1, null=True),
        ),
    ]
