# Generated by Django 3.0.3 on 2020-03-30 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_orderrequest_menu_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='comments',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
