# Generated by Django 3.0.3 on 2020-04-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_menuitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
