# Generated by Django 3.0.3 on 2020-03-30 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20200330_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderrequest',
            name='comments',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderrequest',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
