# Generated by Django 3.0.3 on 2020-04-17 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0007_menuitem_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Pending'), (3, 'Completed')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderlist',
            name='table_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
