# Generated by Django 3.0.3 on 2020-04-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20200418_1725'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaiterCalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.TimeField(auto_now_add=True)),
                ('table_number', models.PositiveSmallIntegerField()),
                ('caller', models.PositiveSmallIntegerField(choices=[(1, 'Kitchen'), (2, 'Customer')])),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='orderlist',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Received'), (3, 'Preparing'), (4, 'Cooking'), (5, 'Pickup ready'), (6, 'Served'), (7, 'Paid')]),
        ),
    ]
