# Generated by Django 3.0.3 on 2020-04-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20200419_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Received'), (3, 'Preparing'), (4, 'Cooking'), (5, 'Pickup ready'), (6, 'Served'), (7, 'Awaiting Payment'), (8, 'Paid')]),
        ),
    ]
