# Generated by Django 3.0.3 on 2020-04-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_auto_20200420_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='total_tables',
            field=models.IntegerField(default=20),
            preserve_default=False,
        ),
    ]
