# Generated by Django 3.0.3 on 2020-04-20 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_restaurant_total_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlist',
            name='table_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_lists', to='customer.Table'),
        ),
    ]
